albert:    20
alice:     20
ann:       40
anna:      40
annie:     40
arthur:    40
bernard:   80
bette:     80
bettie:    80
betty:     80
carl:      120
catherine: 120
charles:   140
dorthy:    180
edward:    220
elizabeth: 220
florence:  260
donald:    180
clara:     140
frank:     260
george:    300
grace:     300
harold:    340
harriet:   340
harry:     360
hazel:     360
helen:     380
henry:     380
james:     440
jane:      440
jayne:     440
jean:      460
joan:      480
john:      460
joseph:    480
margaret:  560
martin:    560
marvin:    580
mary:      580
melvin:    600
mildred:   600
patricia:  680
paul:      680
richard:   740
robert:    760
ruby:      740
ruth:      760
thelma:    820
thomas:    820
walter:    900
wanda:     900
william:   920
wilma:     920
